name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        uses: ./

      - name: Show git config
        run: cat .git/config

      - name: Verify tools are installed
        run: git show-upstream
