name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        uses: ./

      - name: Verify tools are installed
        shell: pwsh
        run: |
          get-command git-add-upstream.ps1
          get-command git-new.ps1
          get-command git-pull-upstream.ps1
          get-command git-rc.ps1
          get-command git-release.ps1
          get-command git-show-upstream.ps1
          get-command git-verify-updated.ps1
